'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Textarea } from '@/components/ui/textarea'
import { Input } from '@/components/ui/input'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { Mail, RefreshCw, Send, Eye, CheckCircle2, ArrowLeft, Download, Loader2 } from 'lucide-react'
import { useToast } from '@/components/ui/use-toast'
import { formatDateTime } from '@/lib/utils'

interface EmailDraftItem {
  id: string
  subject: string
  body: string
  attachments: Array<{ filename: string; path: string; mimeType: string }>
  status: string
  autoGenerated: boolean
  blueprintId?: string
  createdAt: string
  updatedAt: string
  reviewedAt?: string
  sentAt?: string
  workflow: {
    id: string
    application: {
      id: string
      fullName: string
      email: string
    }
  }
  blueprint?: {
    id: string
    status: string
    pdfPath?: string
  }
}

export default function EmailDraftsPage() {
  const { toast } = useToast()
  const [drafts, setDrafts] = useState<EmailDraftItem[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [selectedDraft, setSelectedDraft] = useState<EmailDraftItem | null>(null)
  const [isSending, setIsSending] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const [editedSubject, setEditedSubject] = useState('')
  const [editedBody, setEditedBody] = useState('')

  const fetchDrafts = async () => {
    setIsLoading(true)
    try {
      const response = await fetch('/api/email-drafts')
      const result = await response.json()

      if (result.success) {
        setDrafts(result.data)
      } else {
        toast({
          title: 'Error',
          description: 'Failed to load email drafts',
          variant: 'destructive',
        })
      }
    } catch (error) {
      toast({
        title: 'Error',
        description: 'Failed to load email drafts',
        variant: 'destructive',
      })
    } finally {
      setIsLoading(false)
    }
  }

  useEffect(() => {
    fetchDrafts()
  }, [])

  const handleViewDraft = (draft: EmailDraftItem) => {
    setSelectedDraft(draft)
    setEditedSubject(draft.subject)
    setEditedBody(draft.body)
  }

  const handleSaveDraft = async () => {
    if (!selectedDraft) return

    setIsSaving(true)
    try {
      const response = await fetch('/api/email-drafts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'update',
          draftId: selectedDraft.id,
          subject: editedSubject,
          body: editedBody,
        }),
      })

      const result = await response.json()

      if (result.success) {
        await fetchDrafts()
        setSelectedDraft((prev) =>
          prev ? { ...prev, subject: editedSubject, body: editedBody } : null
        )
        toast({
          title: 'Saved',
          description: 'Email draft has been updated',
        })
      } else {
        throw new Error(result.error || 'Failed to save draft')
      }
    } catch (error) {
      toast({
        title: 'Error',
        description: error instanceof Error ? error.message : 'Failed to save draft',
        variant: 'destructive',
      })
    } finally {
      setIsSaving(false)
    }
  }

  const handleApproveAndSend = async () => {
    if (!selectedDraft) return

    setIsSending(true)
    try {
      // First approve
      const approveResponse = await fetch('/api/email-drafts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'approve',
          draftId: selectedDraft.id,
        }),
      })

      const approveResult = await approveResponse.json()

      if (!approveResult.success) {
        throw new Error(approveResult.error || 'Failed to approve draft')
      }

      // Then send
      const sendResponse = await fetch(`/api/email-drafts/${selectedDraft.id}/send`, {
        method: 'POST',
      })

      const sendResult = await sendResponse.json()

      if (!sendResult.success) {
        throw new Error(sendResult.error || 'Failed to send email')
      }

      toast({
        title: 'Email sent successfully',
        description: `Email has been sent to ${selectedDraft.workflow.application.email}`,
      })

      setSelectedDraft(null)
      await fetchDrafts()
    } catch (error) {
      toast({
        title: 'Error',
        description: error instanceof Error ? error.message : 'Failed to send email',
        variant: 'destructive',
      })
    } finally {
      setIsSending(false)
    }
  }

  const getStatusBadge = (status: string) => {
    const statusConfig: Record<string, { variant: any; label: string }> = {
      PENDING_REVIEW: { variant: 'warning' as const, label: 'Pending Review' },
      MODIFIED: { variant: 'info' as const, label: 'Modified' },
      APPROVED: { variant: 'success' as const, label: 'Approved' },
      SENT: { variant: 'default' as const, label: 'Sent' },
    }

    const config = statusConfig[status] || { variant: 'default' as const, label: status }
    return <Badge variant={config.variant}>{config.label}</Badge>
  }

  // Single email view
  if (selectedDraft) {
    return (
      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <Button variant="outline" onClick={() => setSelectedDraft(null)}>
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to List
          </Button>
          <div>
            <h1 className="text-2xl font-bold">Email Draft</h1>
            <p className="text-muted-foreground">
              Review and edit the email before sending
            </p>
          </div>
        </div>

        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <div className="flex-1">
                <label className="text-sm font-medium text-muted-foreground">Subject</label>
                <Input
                  value={editedSubject}
                  onChange={(e) => setEditedSubject(e.target.value)}
                  className="mt-1"
                />
              </div>
              <div className="ml-4 text-right">
                <div className="text-sm text-muted-foreground">Recipient</div>
                <div className="font-medium">{selectedDraft.workflow.application.fullName}</div>
                <div className="text-sm text-muted-foreground">{selectedDraft.workflow.application.email}</div>
              </div>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <label className="text-sm font-medium text-muted-foreground">Message Body</label>
              <Textarea
                value={editedBody}
                onChange={(e) => setEditedBody(e.target.value)}
                rows={20}
                className="mt-1 font-mono text-sm"
              />
            </div>

            {selectedDraft.attachments && selectedDraft.attachments.length > 0 && (
              <div>
                <label className="text-sm font-medium text-muted-foreground">Attachments</label>
                <div className="mt-2 space-y-2">
                  {selectedDraft.attachments.map((attachment, index) => (
                    <div key={index} className="flex items-center gap-2 p-2 border rounded">
                      <Download className="h-4 w-4" />
                      <span className="text-sm">{attachment.filename}</span>
                      {attachment.path && (
                        <Button size="sm" variant="outline" asChild>
                          <a
                            href={`${process.env.BLUEPRINT_ENGINE_URL || 'http://localhost:3010'}${attachment.path}`}
                            target="_blank"
                            rel="noopener noreferrer"
                          >
                            View
                          </a>
                        </Button>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div className="flex items-center gap-4 border-t pt-4">
              <div className="flex items-center gap-2">
                <span className="text-sm text-muted-foreground">Status:</span>
                {getStatusBadge(selectedDraft.status)}
              </div>
              {selectedDraft.autoGenerated && (
                <Badge variant="outline" className="text-xs">
                  Auto-generated
                </Badge>
              )}
              {selectedDraft.blueprintId && (
                <Badge variant="outline" className="text-xs">
                  Blueprint Email
                </Badge>
              )}
            </div>

            <div className="flex gap-3 border-t pt-4">
              <Button
                onClick={handleSaveDraft}
                disabled={isSaving}
                variant="outline"
              >
                {isSaving ? (
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                ) : null}
                Save Changes
              </Button>
              <Button
                onClick={handleApproveAndSend}
                disabled={isSending || selectedDraft.status === 'SENT'}
              >
                {isSending ? (
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                ) : (
                  <Send className="h-4 w-4 mr-2" />
                )}
                {isSending ? 'Sending...' : 'Approve & Send'}
              </Button>
              {selectedDraft.blueprintId && (
                <Button variant="outline" asChild>
                  <Link href={`/blueprints`}>
                    View Blueprint
                  </Link>
                </Button>
              )}
            </div>
          </CardContent>
        </Card>
      </div>
    )
  }

  // Email drafts list view
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Email Drafts</h1>
          <p className="text-muted-foreground">
            Review and approve email drafts before sending
          </p>
        </div>
        <Button onClick={fetchDrafts} variant="outline" size="sm">
          <RefreshCw className={`h-4 w-4 mr-2 ${isLoading ? 'animate-spin' : ''}`} />
          Refresh
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Email Drafts</CardTitle>
          <CardDescription>
            {drafts.length} draft{drafts.length !== 1 ? 's' : ''} {drafts.filter(d => d.status === 'PENDING_REVIEW').length} pending review
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
            </div>
          ) : drafts.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              <Mail className="h-12 w-12 mx-auto mb-4 opacity-50" />
              <p>No email drafts found</p>
              <p className="text-sm mt-2">
                Email drafts will be automatically generated when blueprints are completed
              </p>
            </div>
          ) : (
            <div className="rounded-md border">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Recipient</TableHead>
                    <TableHead>Subject</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Created</TableHead>
                    <TableHead className="text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {drafts.map((draft) => (
                    <TableRow key={draft.id}>
                      <TableCell>
                        <div>
                          <div className="font-medium">
                            {draft.workflow.application.fullName}
                          </div>
                          <div className="text-sm text-muted-foreground">
                            {draft.workflow.application.email}
                          </div>
                        </div>
                      </TableCell>
                      <TableCell className="max-w-md">
                        <div className="truncate">{draft.subject}</div>
                      </TableCell>
                      <TableCell>
                        <div className="flex gap-1">
                          {draft.blueprintId ? (
                            <Badge variant="secondary" className="text-xs">
                              Blueprint
                            </Badge>
                          ) : (
                            <Badge variant="outline" className="text-xs">
                              Manual
                            </Badge>
                          )}
                          {draft.autoGenerated && (
                            <Badge variant="outline" className="text-xs">
                              Auto
                            </Badge>
                          )}
                        </div>
                      </TableCell>
                      <TableCell>{getStatusBadge(draft.status)}</TableCell>
                      <TableCell className="text-sm text-muted-foreground">
                        {formatDateTime(draft.createdAt)}
                      </TableCell>
                      <TableCell className="text-right">
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => handleViewDraft(draft)}
                        >
                          <Eye className="h-4 w-4 mr-2" />
                          Review
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
