'use client'

import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { CheckCircle, Clock, FileText, Sparkles } from 'lucide-react'

export default function ApplyPage() {
  const router = useRouter()

  const benefits = [
    {
      icon: Sparkles,
      title: 'AI-Powered Strategy',
      description: 'Get personalized business plans generated by our advanced AI system'
    },
    {
      icon: FileText,
      title: 'Professional Documents',
      description: 'Receive beautifully designed deliverables and brand assets'
    },
    {
      icon: Clock,
      title: 'Quick Turnaround',
      description: 'From application to launch in weeks, not months'
    },
    {
      icon: CheckCircle,
      title: 'Dedicated Support',
      description: 'Work directly with our team throughout your journey'
    }
  ]

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      {/* Hero Section */}
      <div className="text-center space-y-4">
        <h1 className="text-4xl font-bold text-slate-900">
          Launch Your Brand with Wavelaunch
        </h1>
        <p className="text-lg text-slate-600 max-w-2xl mx-auto">
          Join our creator partnership program and transform your vision into a thriving brand.
          We&apos;ll guide you every step of the way.
        </p>
      </div>

      {/* Benefits Grid */}
      <div className="grid md:grid-cols-2 gap-4">
        {benefits.map((benefit) => (
          <Card key={benefit.title} className="border-slate-200">
            <CardContent className="pt-6">
              <div className="flex items-start gap-4">
                <div className="p-2 rounded-lg bg-blue-50">
                  <benefit.icon className="h-5 w-5 text-blue-600" />
                </div>
                <div>
                  <h3 className="font-semibold text-slate-900">{benefit.title}</h3>
                  <p className="text-sm text-slate-500">{benefit.description}</p>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Application Info Card */}
      <Card className="border-blue-200 bg-blue-50/50">
        <CardHeader>
          <CardTitle>Application Process</CardTitle>
          <CardDescription>What to expect when you apply</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid md:grid-cols-3 gap-4">
            <div className="text-center p-4">
              <div className="w-8 h-8 rounded-full bg-blue-600 text-white flex items-center justify-center mx-auto mb-2 font-semibold">
                1
              </div>
              <h4 className="font-medium text-slate-900">Complete Form</h4>
              <p className="text-sm text-slate-500">Fill out our comprehensive intake form (15-20 min)</p>
            </div>
            <div className="text-center p-4">
              <div className="w-8 h-8 rounded-full bg-blue-600 text-white flex items-center justify-center mx-auto mb-2 font-semibold">
                2
              </div>
              <h4 className="font-medium text-slate-900">Review</h4>
              <p className="text-sm text-slate-500">Our team reviews your application within 48 hours</p>
            </div>
            <div className="text-center p-4">
              <div className="w-8 h-8 rounded-full bg-blue-600 text-white flex items-center justify-center mx-auto mb-2 font-semibold">
                3
              </div>
              <h4 className="font-medium text-slate-900">Get Started</h4>
              <p className="text-sm text-slate-500">If approved, we begin your brand journey</p>
            </div>
          </div>

          <div className="text-center pt-4">
            <Button
              size="lg"
              onClick={() => router.push('/apply/form')}
              className="px-8"
            >
              Start Application
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* FAQ Section */}
      <Card>
        <CardHeader>
          <CardTitle>Frequently Asked Questions</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <h4 className="font-medium text-slate-900">How long does the application take?</h4>
            <p className="text-sm text-slate-500">The form takes about 15-20 minutes to complete thoroughly.</p>
          </div>
          <div>
            <h4 className="font-medium text-slate-900">What information do I need?</h4>
            <p className="text-sm text-slate-500">Basic contact info, your social media handles, and details about your vision and goals. Having brand inspiration images ready helps too.</p>
          </div>
          <div>
            <h4 className="font-medium text-slate-900">Can I save and continue later?</h4>
            <p className="text-sm text-slate-500">The form keeps your progress in the browser, but we recommend completing it in one session for the best experience.</p>
          </div>
          <div>
            <h4 className="font-medium text-slate-900">When will I hear back?</h4>
            <p className="text-sm text-slate-500">Our team reviews applications within 48 hours and will contact you via email.</p>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
