'use client';

import { useEffect, useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { EmailEditor } from '@/components/emails/email-editor';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Mail, RefreshCw, Send, Eye } from 'lucide-react';
import { toast } from '@/components/ui/use-toast';
import { formatDateTime } from '@/lib/utils';

interface EmailDraftItem {
  id: string;
  subject: string;
  body: string;
  attachments: any[];
  status: string;
  createdAt: Date;
  autoGenerated: boolean;
  blueprintId?: string;
  workflow: {
    id: string;
    application: {
      id: string;
      fullName: string;
      email: string;
    };
  };
}

export default function EmailsPage() {
  const [drafts, setDrafts] = useState<EmailDraftItem[]>([]);
  const [filteredDrafts, setFilteredDrafts] = useState<EmailDraftItem[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [selectedDraft, setSelectedDraft] = useState<EmailDraftItem | null>(null);
  const [isSending, setIsSending] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [filterType, setFilterType] = useState<'all' | 'blueprint' | 'manual'>('all');

  const fetchDrafts = async () => {
    setIsLoading(true);
    try {
      const response = await fetch('/api/workflow/emails');
      const result = await response.json();

      if (result.success) {
        setDrafts(result.data);
        setFilteredDrafts(result.data);
      } else {
        toast({
          title: 'Error',
          description: 'Failed to load email drafts',
          variant: 'destructive',
        });
      }
    } catch (error) {
      toast({
        title: 'Error',
        description: 'Failed to load email drafts',
        variant: 'destructive',
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleSaveDraft = async (subject: string, body: string) => {
    if (!selectedDraft) return;

    setIsSaving(true);
    try {
      const response = await fetch('/api/workflow/emails', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'update',
          draftId: selectedDraft.id,
          subject,
          body,
        }),
      });

      const result = await response.json();

      if (result.success) {
        await fetchDrafts();
        setSelectedDraft((prev) =>
          prev ? { ...prev, subject, body } : null
        );
      } else {
        throw new Error(result.error || 'Failed to save draft');
      }
    } catch (error) {
      toast({
        title: 'Error',
        description: 'Failed to save draft',
        variant: 'destructive',
      });
      throw error;
    } finally {
      setIsSaving(false);
    }
  };

  const handleApproveAndSend = async () => {
    if (!selectedDraft) return;

    setIsSending(true);
    try {
      // First approve
      const approveResponse = await fetch('/api/workflow/emails', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'approve',
          draftId: selectedDraft.id,
        }),
      });

      const approveResult = await approveResponse.json();

      if (!approveResult.success) {
        throw new Error(approveResult.error || 'Failed to approve draft');
      }

      // Then send
      const sendResponse = await fetch(`/api/workflow/emails/${selectedDraft.id}/send`, {
        method: 'POST',
      });

      const sendResult = await sendResponse.json();

      if (!sendResult.success) {
        throw new Error(sendResult.error || 'Failed to send email');
      }

      toast({
        title: 'Email sent successfully',
        description: `Email has been sent to ${selectedDraft.workflow.application.email}`,
      });

      setSelectedDraft(null);
      await fetchDrafts();
    } catch (error) {
      toast({
        title: 'Error',
        description: error instanceof Error ? error.message : 'Failed to send email',
        variant: 'destructive',
      });
    } finally {
      setIsSending(false);
    }
  };

  useEffect(() => {
    fetchDrafts();
  }, []);

  useEffect(() => {
    if (filterType === 'all') {
      setFilteredDrafts(drafts);
    } else if (filterType === 'blueprint') {
      setFilteredDrafts(drafts.filter(d => d.blueprintId));
    } else if (filterType === 'manual') {
      setFilteredDrafts(drafts.filter(d => !d.blueprintId));
    }
  }, [drafts, filterType]);

  const getStatusBadge = (status: string) => {
    const statusConfig: Record<string, { variant: any; label: string }> = {
      PENDING_REVIEW: { variant: 'warning', label: 'Pending Review' },
      MODIFIED: { variant: 'info', label: 'Modified' },
      APPROVED: { variant: 'success', label: 'Approved' },
      SENT: { variant: 'default', label: 'Sent' },
    };

    const config = statusConfig[status] || { variant: 'default', label: status };
    return <Badge variant={config.variant}>{config.label}</Badge>;
  };

  if (selectedDraft) {
    return (
      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <Button variant="outline" onClick={() => setSelectedDraft(null)}>
            ← Back to List
          </Button>
          <div>
            <h1 className="text-2xl font-bold">Edit Email Draft</h1>
            <p className="text-muted-foreground">
              Review and edit the email before sending
            </p>
          </div>
        </div>

        <EmailEditor
          initialSubject={selectedDraft.subject}
          initialBody={selectedDraft.body}
          attachments={selectedDraft.attachments}
          recipientEmail={selectedDraft.workflow.application.email}
          recipientName={selectedDraft.workflow.application.fullName}
          onSave={handleSaveDraft}
          onSend={handleApproveAndSend}
          isSaving={isSaving}
          isSending={isSending}
        />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Email Drafts</h1>
          <p className="text-muted-foreground">
            Review and approve email drafts before sending
          </p>
        </div>
        <Button onClick={fetchDrafts} variant="outline" size="sm">
          <RefreshCw className={`h-4 w-4 mr-2 ${isLoading ? 'animate-spin' : ''}`} />
          Refresh
        </Button>
      </div>

      {/* Filter Tabs */}
      <div className="flex items-center gap-2">
        <Button
          variant={filterType === 'all' ? 'default' : 'outline'}
          size="sm"
          onClick={() => setFilterType('all')}
        >
          All ({drafts.length})
        </Button>
        <Button
          variant={filterType === 'blueprint' ? 'default' : 'outline'}
          size="sm"
          onClick={() => setFilterType('blueprint')}
        >
          Blueprint Emails ({drafts.filter(d => d.blueprintId).length})
        </Button>
        <Button
          variant={filterType === 'manual' ? 'default' : 'outline'}
          size="sm"
          onClick={() => setFilterType('manual')}
        >
          Manual Emails ({drafts.filter(d => !d.blueprintId).length})
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>
            {filterType === 'all' && 'All Email Drafts'}
            {filterType === 'blueprint' && 'Blueprint Approval Emails'}
            {filterType === 'manual' && 'Manual Email Drafts'}
          </CardTitle>
          <CardDescription>
            {filteredDrafts.length} draft{filteredDrafts.length !== 1 ? 's' : ''} awaiting approval
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="flex items-center justify-center py-12">
              <RefreshCw className="h-8 w-8 animate-spin text-muted-foreground" />
            </div>
          ) : filteredDrafts.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              <Mail className="h-12 w-12 mx-auto mb-4 opacity-50" />
              <p>No email drafts found</p>
              <p className="text-sm mt-2">
                Drafts will be created automatically after blueprints are generated
              </p>
            </div>
          ) : (
            <div className="rounded-md border">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Recipient</TableHead>
                    <TableHead>Subject</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Created</TableHead>
                    <TableHead className="text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredDrafts.map((draft) => (
                    <TableRow key={draft.id}>
                      <TableCell>
                        <div>
                          <div className="font-medium">
                            {draft.workflow.application.fullName}
                          </div>
                          <div className="text-sm text-muted-foreground">
                            {draft.workflow.application.email}
                          </div>
                        </div>
                      </TableCell>
                      <TableCell className="max-w-md">
                        <div className="truncate">{draft.subject}</div>
                      </TableCell>
                      <TableCell>
                        {draft.blueprintId ? (
                          <Badge variant="secondary" className="text-xs">
                            Blueprint
                          </Badge>
                        ) : (
                          <Badge variant="outline" className="text-xs">
                            Manual
                          </Badge>
                        )}
                        {draft.autoGenerated && (
                          <Badge variant="outline" className="text-xs ml-1">
                            Auto
                          </Badge>
                        )}
                      </TableCell>
                      <TableCell>{getStatusBadge(draft.status)}</TableCell>
                      <TableCell className="text-sm text-muted-foreground">
                        {formatDateTime(draft.createdAt)}
                      </TableCell>
                      <TableCell className="text-right">
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => setSelectedDraft(draft)}
                        >
                          <Eye className="h-4 w-4 mr-2" />
                          Review
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
