import { db } from '@/lib/db/prisma';
import type { Blueprint, Application, EmailDraft, DraftStatus } from '@prisma/client';

export interface BlueprintEmailDraftData {
  subject: string;
  body: string;
  attachments?: Array<{
    filename: string;
    path: string;
    mimeType: string;
  }>;
}

export interface BlueprintEmailComposerOptions {
  fromEmail: string;
  fromName: string;
  appUrl: string;
  blueprintEngineUrl?: string;
}

export interface TemplateVariables {
  firstName: string;
  clientName: string;
  industryNiche: string;
  visionSummary: string;
  targetAudience: string;
  differentiation: string;
  brandValues: string;
  country: string;
  developmentTimeline: string;
  investmentRange: string;
  equitySplit: string;
  wavelaunchEquity: string;
  commitmentFee: string;
  pdfUrl?: string;
  appUrl: string;
  reviewUrl?: string;
}

/**
 * BlueprintEmailComposer - Generates personalized approval emails for completed blueprints
 *
 * This service creates email drafts when a blueprint status changes to COMPLETE or APPROVED.
 * It extracts key metrics from the blueprint and application data to generate personalized
 * email content.
 */
export class BlueprintEmailComposer {
  private options: BlueprintEmailComposerOptions;

  constructor(options: BlueprintEmailComposerOptions) {
    this.options = options;
    this.options.appUrl = options.appUrl || process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3007';
    this.options.blueprintEngineUrl = options.blueprintEngineUrl || process.env.BLUEPRINT_ENGINE_URL || 'http://localhost:3010';
  }

  /**
   * Generate approval email draft for a completed blueprint
   */
  async generateApprovalDraft(blueprintId: string): Promise<BlueprintEmailDraftData & { workflowId?: string }> {
    const blueprint = await db.blueprint.findUnique({
      where: { id: blueprintId },
      include: {
        application: true,
      },
    });

    if (!blueprint) {
      throw new Error('Blueprint not found');
    }

    if (blueprint.status !== 'COMPLETE' && blueprint.status !== 'APPROVED') {
      throw new Error(`Blueprint must be COMPLETE or APPROVED to generate approval email. Current status: ${blueprint.status}`);
    }

    // Get workflow state for this application
    const workflowState = await db.workflowState.findUnique({
      where: { applicationId: blueprint.application.id },
    });

    if (!workflowState) {
      throw new Error('Workflow state not found for this application');
    }

    const application = blueprint.application;
    const variables = this.extractTemplateVariables(application, blueprint);

    const subject = 'Your Business Blueprint is Ready for Review 📊';
    const body = this.buildEmailBody(variables);
    const attachments = this.buildAttachments(blueprint, application);

    return {
      subject,
      body,
      attachments,
      workflowId: workflowState.id,
    };
  }

  /**
   * Save email draft to database
   */
  async saveDraft(
    workflowId: string,
    blueprintId: string,
    draftData: BlueprintEmailDraftData
  ): Promise<EmailDraft> {
    // Check if a draft already exists for this blueprint
    const existingDraft = await db.emailDraft.findFirst({
      where: {
        blueprintId,
      },
    });

    if (existingDraft) {
      // Update existing draft
      return db.emailDraft.update({
        where: { id: existingDraft.id },
        data: {
          subject: draftData.subject,
          body: draftData.body,
          attachments: draftData.attachments || [],
          status: 'PENDING_REVIEW' as DraftStatus,
          autoGenerated: true,
          updatedAt: new Date(),
        },
      });
    }

    // Create new draft
    return db.emailDraft.create({
      data: {
        workflowId,
        blueprintId,
        subject: draftData.subject,
        body: draftData.body,
        attachments: draftData.attachments || [],
        status: 'PENDING_REVIEW' as DraftStatus,
        autoGenerated: true,
      },
    });
  }

  /**
   * Extract template variables from application and blueprint data
   */
  private extractTemplateVariables(application: Application, blueprint: Blueprint): TemplateVariables {
    const firstName = application.fullName.split(' ')[0];

    // Extract first sentence from vision for summary
    const visionSummary = (application.visionForVenture || '')
      .split('.')
      .filter(Boolean)
      .slice(0, 2)
      .join('. ')
      .trim() || application.visionForVenture;

    // Extract first sentence from differentiation
    const differentiation = (application.differentiation || '')
      .split('.')
      .filter(Boolean)
      .slice(0, 1)
      .join('. ')
      .trim() || application.differentiation;

    // Build PDF URL if available
    let pdfUrl: string | undefined;
    if (blueprint.pdfPath) {
      pdfUrl = `${this.options.blueprintEngineUrl}${blueprint.pdfPath}`;
    }

    // Build review URL (could link to a client portal or blueprint preview)
    const reviewUrl = `${this.options.appUrl}/blueprints/${blueprint.id}`;

    return {
      firstName,
      clientName: application.fullName,
      industryNiche: application.industryNiche,
      visionSummary,
      targetAudience: application.targetAudience,
      differentiation,
      brandValues: application.brandValues,
      country: application.country,
      developmentTimeline: '8 months',
      investmentRange: '$150K-$200K',
      equitySplit: '90%',
      wavelaunchEquity: '10%',
      commitmentFee: '$5,000',
      pdfUrl,
      appUrl: this.options.appUrl,
      reviewUrl,
    };
  }

  /**
   * Build personalized email body with template variables
   */
  private buildEmailBody(variables: TemplateVariables): string {
    const {
      firstName,
      clientName,
      industryNiche,
      visionSummary,
      targetAudience,
      differentiation,
      brandValues,
      country,
      developmentTimeline,
      investmentRange,
      equitySplit,
      wavelaunchEquity,
      commitmentFee,
      pdfUrl,
      appUrl,
    } = variables;

    let body = `Hi ${firstName},

Great news! Your comprehensive Business Blueprint has been completed and is ready for your review.

This McKinsey-caliber 15-25 page business plan includes:
- Market Sizing & Competitive Intelligence
- Audience Deep Dive & Brand Positioning
- Product Architecture & Financial Projections
- Go-to-Market Strategy & Implementation Roadmap

YOUR UNIQUE MARKET POSITION:
Based on your background in ${industryNiche} and your vision to ${visionSummary}, we see a credible path to building a scalable brand in the ${targetAudience} market.

KEY METRICS:
- Development Timeline: ${developmentTimeline}
- Investment Range: ${investmentRange}

KEY HIGHLIGHTS FROM YOUR BLUEPRINT:
- Your audience of ${targetAudience} represents a substantial market opportunity
- Your differentiation around ${differentiation} can create a real competitive edge
- Your brand values of ${brandValues} resonate strongly with your target demographic

INVESTMENT STRUCTURE:
- Equity Split: ${equitySplit} Creator / ${wavelaunchEquity} Wavelaunch
- Commitment Fee: ${commitmentFee}
- Investment Range: ${investmentRange}
`;

    if (pdfUrl) {
      body += `
DOWNLOAD YOUR BLUEPRINT:
${pdfUrl}
`;
    }

    body += `
NEXT STEPS:
1. Review the Executive Summary and Strategic Recommendations
2. Check the Financial Projections and Go-to-Market Strategy
3. Reply with 2-3 times for a 30-min call to discuss the blueprint
4. If aligned, we'll begin with the onboarding to start execution

This blueprint is tailored to your exact Vision Form responses and your current context in ${country}.

If you have any constraints (timeline, capacity, budget, product preferences) that should shape our recommendation, reply with them and we'll incorporate them into our discussion.

Best regards,
The Wavelaunch Studio Team

---
Wavelaunch Studio | Building Brands for Creators
${appUrl}
`;

    return body;
  }

  /**
   * Build attachments array (including PDF if available)
   */
  private buildAttachments(blueprint: Blueprint, application: Application): Array<{
    filename: string;
    path: string;
    mimeType: string;
  }> {
    const attachments: Array<{
      filename: string;
      path: string;
      mimeType: string;
    }> = [];

    // Add PDF if available
    if (blueprint.pdfPath) {
      // Sanitize client name for filename
      const sanitizedName = application.fullName
        .replace(/[^a-zA-Z0-9\s]/g, '')
        .replace(/\s+/g, '_');

      attachments.push({
        filename: `${sanitizedName}_Blueprint.pdf`,
        path: blueprint.pdfPath,
        mimeType: 'application/pdf',
      });
    }

    return attachments;
  }

  /**
   * Get existing draft for a blueprint
   */
  async getDraftByBlueprint(blueprintId: string): Promise<EmailDraft | null> {
    return db.emailDraft.findFirst({
      where: { blueprintId },
      orderBy: { createdAt: 'desc' },
    });
  }

  /**
   * Check if blueprint has an existing draft
   */
  async hasDraft(blueprintId: string): Promise<boolean> {
    const count = await db.emailDraft.count({
      where: { blueprintId },
    });
    return count > 0;
  }
}
